sudo: false
dist: trusty
addons:
    apt:
        packages:
            - language-pack-zh-hans
cache: pip
language: python
python:
    - 3.6
before_install:
    - curl -JOL 'https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh'
    - bash install.sh
    - source $HOME/.nvm/nvm.sh
    - nvm install node
    - nvm use node
    - npm install -g less
install:
    - pip install -r tools/requirements.txt
env:
    - PIP=pip PY=python PELICAN=pelican
script:
    - mkdir -p build/venv
    - touch build/venv/pip-selfcheck.json
    - make publish
before_deploy:
    - openssl aes-256-cbc -K $encrypted_730350046d35_key -iv $encrypted_730350046d35_iv -in tools/deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
    - mkdir -p $HOME/.ssh
    - echo -e 'Host archvps\n\tUser aetf\n\tHostName archvps.unlimitedcodeworks.xyz\n\tPort 59901' >> $HOME/.ssh/config
    - ssh-keyscan -H -p 59901 archvps.unlimitedcodeworks.xyz 2>&1 | tee -a $HOME/.ssh/known_hosts
deploy:
    provider: script
    skip_cleanup: true
    script: make upload
    on:
        branch: pelican-source
