sudo: false
dist: bionic
addons:
    apt:
        packages:
            - language-pack-zh-hans
language: node_js
node_js:
    - '12'
cache: npm
env:
    - TZ=America/Detroit
before_install:
    - env NOKOGIRI_USE_SYSTEM_LIBRARIES=true gem install html-proofer
    - npm install -g hexo-cli
# default install will use npm ci
script:
    - npm run build
    - npm test
before_deploy:
    - openssl aes-256-cbc -K $encrypted_730350046d35_key -iv $encrypted_730350046d35_iv -in tools/deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
    - mkdir -p $HOME/.ssh
    - echo -e 'Host archvps\n\tUser aetf\n\tHostName archvps.unlimitedcodeworks.xyz\n\tPort 59901' >> $HOME/.ssh/config
    - ssh-keyscan -H -p 59901 archvps.unlimitedcodeworks.xyz 2>&1 | tee -a $HOME/.ssh/known_hosts
deploy:
    provider: script
    skip_cleanup: true
    script: npm run deploy
    on:
        branch: hexo
after_deploy:
    - >-
        curl -X POST "https://api.cloudflare.com/client/v4/zones/$cloudflare_zone_id/purge_cache"
        -H "X-Auth-Email: $cloudflare_user_email"
        -H "X-Auth-Key: $cloudflare_api_key"
        -H "Content-Type: application/json"
        --data '{"purge_everything":true}'
