sudo: false
dist: trusty
addons:
    ssh_known_hosts: archvps.unlimitedcodeworks.xyz
    apt:
        packages:
            - language-pack-zh-hans
language: python
python:
    - 3.6
install:
    - pip install -r tools/requirements.txt
env:
    - PIP=pip PY=python PELICAN=pelican
script:
    - locale -a
    - mkdir -p tools/venv
    - touch tools/venv/pip-selfcheck.json
    - make publish
before_deploy:
    - openssl aes-256-cbc -K $encrypted_730350046d35_key -iv $encrypted_730350046d35_iv -in tools/deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmood 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
deploy:
    provider: script
    skip_cleanup: true
    script: make upload
    on:
        branch: pelican-source
