# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Unlimited Code Works
subtitle:
description:
author: Peifeng Yu
timezone: America/Detroit
language:
    - en
    - zh-Hans

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://unlimitedcodeworks.xyz
root: /
permalink: blog/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: build/output

tag_dir: tags
archive_dir: archives
category_dir: categories
i18n_dir: 
skip_render:
    - assets/theme/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
    path: '/blog'
    per_page: 10
    order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Markdown rendering
## Markdown-it config
## dependency: hexo-renderer-markdown-it
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
    render:
        html: true
        xhtmlOut: true
        breaks: false
        linkify: true
        typographer: true
        quotes: '“”‘’'
    plugins:
        - markdown-it-abbr
        - markdown-it-footnote
        - markdown-it-ins
        - markdown-it-sub
        - markdown-it-sup
    anchors:
        level: 2
        collisionSuffix: 'v'
        permalink: true
        permalinkClass: header-anchor
        permalinkSymbol: ¶

# Math
## dependency: hexo-math
math:
    engine: 'katex'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: 'page'

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Feed
## dependency: hexo-generator-feed
feed:
    type: atom
    path: atom.xml
    limit: 0
    hub:
    content: true

# Search
## dependency: hexo-generator-searchdb
search:
    path: search.xml
    field: post
    format: raw
    limit: 10000

# Have multiple sizes for images
## dependency: hexo-image-sizes
image_sizes:
    pattern: !!js/regexp /\.(gif|jpg|jpeg|png)$/i
    profiles:
        body:
            width: 700
        thumbnail:
            width: 300
        huge:
            width: 1000
            allowEnlargement: true
    defaultProfile: thumbnail
    link: true
    useAltForTitle: false

# Code highlighting
## disable builtin one
highlight:
    enable: false
## dependency: hexo-prism-plus
code_dir: assets/code
prism_plus:
    enable: true
    # Custom Prism path
    vendors:
        base_url: /assets/theme/
        prism:
            - prism.js
        prism_css:
            - prism.css
    # Default language if not specified inline in code blocks
    default_lang: clike
    # Default preset if no preset is specified inline
    default_preset:
        lineno: true
        classes:
        styles:
            max-height: 30em
    # All available presets
    presets:
        shell:
            lineno: false
            classes: [ command-line ]
            user: aetf
            host: localhost
            styles:
                max-height: 30em

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
    type: rsync
    host: archvps.unlimitedcodeworks.xyz
    user: aetf
    root: /srv/http/blog-rewrite
    port: 59901
    delete: true
    verbose: true
