# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Unlimited Code Works
subtitle: A pessimist because of intelligence, but an optimist because of will.
description:
author: Peifeng Yu
timezone: America/Detroit
language:
    - en
    - zh-CN

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://unlimitedcodeworks.xyz
root: /
permalink: blog/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: build/output

tag_dir: tags
archive_dir: archives
category_dir: categories
i18n_dir:
skip_render:
    - assets/theme/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
    path: '/blog'
    per_page: 10
    order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Tag pages
tag_generator:
    per_page: 10
    enable_index_page: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: 'page'

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Markdown rendering
## Markdown-it config
## dependency: hexo-renderer-markdown-it, markdown-it-anchor, @aetf/markdown-it-katex
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
## Note: hexo-renderer-markdown-it only supports passing in plugin option in master branch later than
##       commit 7d09d25958d3c618b4f049f1995962038d2b829d
## Note: math support also requires math.enabled = true in _data/next.yml
markdown:
    render:
        html: true
        xhtmlOut: true
        breaks: false
        linkify: true
        typographer: true
        quotes: '“”‘’'
    plugins:
        - markdown-it-abbr
        - markdown-it-footnote
        - markdown-it-ins
        - markdown-it-sub
        - markdown-it-sup
        - "@aetf/markdown-it-katex"
        - name: markdown-it-anchor
          options:
              level: 2
              permalink: true
              permalinkClass: header-anchor
              permalinkSymbol: <i class="fa fa-anchor" aria-hidden="true"></i>

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/

# Use the theme-next theme
## theme config override in _data/next.yml
theme: next

# Feed
## dependency: hexo-generator-feed
feed:
    type: atom
    path: atom.xml
    limit: 0
    hub:
    content: true

# Search
## dependency: hexo-generator-searchdb
search:
    path: search.xml
    field: post
    format: raw
    limit: 10000

# Have multiple sizes for images
## dependency: hexo-image-sizes
image_sizes:
    pattern: !!js/regexp /\.(gif|jpg|jpeg|png)$/i
    profiles:
        body:
            width: 700
        thumbnail:
            width: 300
        huge:
            width: 1000
            allowEnlargement: true
    defaultProfile: thumbnail
    link: true
    useAltForTitle: false

# Code highlighting
## disable builtin one
highlight:
    enable: false
## dependency: hexo-prism-plus
code_dir: assets/code
prism_plus:
    enable: true
    # Custom Prism path
    vendors:
        base_url: /assets/theme/
        prism:
            - prism.js
        prism_css:
            - prism.css
    # Default language if not specified inline in code blocks
    default_lang: clike
    # Default preset if no preset is specified inline
    default_preset:
        lineno: true
        classes:
        styles:
            max-height: 30em
    # All available presets
    presets:
        shell:
            lineno: false
            classes: [ command-line ]
            user: aetf
            host: localhost
            styles:
                max-height: 30em

# Auto excerpt
## dependency: hexo-excerpt
excerpt:
    depth: 5
    excerpt_excludes:
        - .header-anchor
        - .note.info

# URL redirection to help migration
## dependency: hexo-alias-generator
alias:
    blog/1970/11/18/a-really-complex-markdown-test/index.html: blog/1970/11/18/complex-md-test/index.html
    blog/2016/05/13/gsoc-communicating-with-lldb/index.html: blog/2016/05/17/gsoc-communicating-with-lldb/index.html
    blog/2016/05/14/gsoc-communicating-with-lldb/index.html: blog/2016/05/17/gsoc-communicating-with-lldb/index.html
    blog/2016/08/21/gsoc-kdevelop-lldb-final-report/index.html: blog/2016/08/20/gsoc-kdevelop-lldb-final-report/index.html
    blog/2016/06/27/gsoc-mid-term-evaluation/index.html: blog/2016/06/29/gsoc-midterm-evaluation/index.html
    blog/2016/06/28/gsoc-mid-term-evaluation/index.html: blog/2016/06/29/gsoc-midterm-evaluation/index.html
    blog/2016/06/10/build-kdevelop-against-custom-kdevplatform/index.html: blog/2016/08/03/build-kdevelop-against-custom-kdevplatform/index.html
    blog/2013/02/05/usaco-241-the-tamworth-two/index.html: blog/2013/02/05/usaco-2-4-1/index.html
    blog/2013/02/16/usaco-314-shaping-regions/index.html: blog/2013/02/16/usaco-3-1-4/index.html
    blog/2013/02/05/usaco-231-longest-prefix/index.html: blog/2013/02/05/usaco-2-3-1/index.html
    blog/2013/02/15/usaco-242-overfencing/index.html: blog/2013/02/15/usaco-2-4-2/index.html
    blog/2013/02/05/usaco-235-controlling-companies/index.html: blog/2013/02/05/usaco-2-3-5/index.html
    blog/2013/02/07/hdu-3234-exclusive-or/index.html: blog/2013/02/07/hdu-3234/index.html
    blog/2013/12/23/njupt-1362-qi-che-jia-you-xing-shi-wen-ti/index.html: blog/2013/12/23/njupt-1362/index.html


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
    type: rsync
    host: archvps.unlimitedcodeworks.xyz
    user: aetf
    root: /srv/http/blog
    port: 59901
    delete: true
    verbose: true
